language: minimal

addons:
  apt:
    update: false
    packages:
     - build-essential
     - gnupg
     - util-linux

dist:
 - bionic

before_install:
 - source .travis/common.sh
 - bash .travis/fixup-git.sh

install:
 - source .travis/common.sh
 - if [[ -z $CPU_VARIANT ]]; then source bootstrap.sh --cpu $CPU --platform $P --target $T --firmware $F; else source bootstrap.sh --cpu $CPU --cpu-variant $CPU_VARIANT --platform $P --target $T --firmware $F; fi
 - bash .travis/setup.sh

script:
 - bash .travis/build.sh

after_failure:
 - bash .travis/after_failure.sh

after_success:
 - bash .travis/after_success.sh

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   # Travis reports incorrect the hosts number of processors, override to 2
   # cores.
   - JOBS=2
  matrix:
   # C=cpu.variant      TC="toolchain" P=platform         T="target1 t2"  F=firmware    A="config1 = value1;config2 = value2"
   #--------------------------------------------
   # Bare-metal firmware, base targets
   #--------------------------------------------
   # LatticeMico32
   - C=lm32             TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=lm32             TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=lm32             TC="vivado"    P=basys3            T="base"       F=hdmi2usb
   - C=lm32             TC="vivado"    P=cmod_a7           T="base"       F=hdmi2usb
   - C=lm32             TC="vivado"    P=mimas_a7          T="base"       F=hdmi2usb
   - C=lm32             TC="vivado"    P=mimas_a7          T="net"        F=hdmi2usb
   - C=lm32             TC="vivado"    P=neso              T="base"       F=hdmi2usb
   - C=lm32             TC="vivado"    P=nexys_video       T="base"       F=hdmi2usb
   - C=lm32             TC="vivado"    P=nexys_video       T="net"        F=hdmi2usb
   - C=lm32             TC="ise"       P=atlys             T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=atlys             T="net"        F=hdmi2usb
   - C=lm32             TC="ise"       P=galatea           T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=mimasv2           T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=minispartan6      T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=opsis             T="net"        F=hdmi2usb
   - C=lm32             TC="ise"       P=pipistrello       T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=saturn            T="base"       F=hdmi2usb
   - C=lm32             TC="ise"       P=waxwing           T="base"       F=hdmi2usb
   - C=lm32.lite        TC="icestorm"  P=ice40_hx8k_b_evn  T="base"       F=stub
   - C=lm32.lite        TC="icestorm"  P=ice40_up5k_b_evn  T="base"       F=stub
   - C=lm32.lite        TC="icestorm"  P=icebreaker        T="base"       F=stub
   - C=lm32.lite        TC="icestorm"  P=tinyfpga_bx       T="base"       F=stub
   - C=lm32.lite        TC="icestorm"  P=upduino_v1        T="base"       F=stub
   - C=lm32.lite        TC="icestorm"  P=icefun            T="base"       F=stub
   - C=lm32.lite        TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=lm32.lite        TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=lm32.lite                       P=opsis             T="base"       F=hdmi2usb
   - C=lm32.lite                       P=opsis             T="net"        F=hdmi2usb
   - C=lm32.minimal     TC="icestorm"  P=ice40_hx8k_b_evn  T="base"       F=stub
   - C=lm32.minimal     TC="icestorm"  P=ice40_up5k_b_evn  T="base"       F=stub
   - C=lm32.minimal     TC="icestorm"  P=icebreaker        T="base"       F=stub
   - C=lm32.minimal     TC="icestorm"  P=tinyfpga_bx       T="base"       F=stub
   - C=lm32.minimal     TC="icestorm"  P=upduino_v1        T="base"       F=stub
   - C=lm32.minimal     TC="icestorm"  P=icefun            T="base"       F=stub
   - C=lm32.minimal     TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=lm32.minimal     TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=lm32.minimal     TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=lm32.minimal     TC="ise"       P=opsis             T="net"        F=hdmi2usb
   # OpenRISC1000    F=hdmi2usb
   - C=mor1kx           TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=mor1kx           TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=mor1kx           TC="vivado"    P=mimas_a7          T="base"       F=hdmi2usb
   - C=mor1kx           TC="vivado"    P=mimas_a7          T="net"        F=hdmi2usb
   - C=mor1kx           TC="vivado"    P=atlys             T="base"       F=hdmi2usb
   - C=mor1kx           TC="vivado"    P=atlys             T="net"        F=hdmi2usb
   - C=mor1kx           TC="ise"       P=mimasv2           T="base"       F=hdmi2usb
   - C=mor1kx           TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=mor1kx           TC="ise"       P=opsis             T="net"        F=hdmi2usb
   - C=mor1kx           TC="ise"       P=pipistrello       T="base"       F=hdmi2usb
   # VexRISCV    F=hdmi2usb
   - C=vexriscv         TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=vexriscv         TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=vexriscv         TC="vivado"    P=mimas_a7          T="base"       F=hdmi2usb
   - C=vexriscv         TC="vivado"    P=mimas_a7          T="net"        F=hdmi2usb
   - C=vexriscv         TC="ise"       P=mimasv2           T="base"       F=hdmi2usb
   - C=vexriscv         TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=vexriscv         TC="ise"       P=opsis             T="net"        F=hdmi2usb
   - C=vexriscv.lite    TC="icestorm"  P=ice40_hx8k_b_evn  T="base"       F=stub
   - C=vexriscv.lite    TC="icestorm"  P=ice40_up5k_b_evn  T="base"       F=stub
   - C=vexriscv.lite    TC="icestorm"  P=icebreaker        T="base"       F=stub
   - C=vexriscv.lite    TC="icestorm"  P=tinyfpga_bx       T="base"       F=stub
   - C=vexriscv.lite    TC="icestorm"  P=upduino_v1        T="base"       F=stub
   - C=vexriscv.lite    TC="icestorm"  P=icefun            T="base"       F=stub
   - C=vexriscv.lite    TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=vexriscv.lite    TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=vexriscv.lite    TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=vexriscv.lite    TC="ise"       P=opsis             T="net"        F=hdmi2usb
   - C=vexriscv.lite    TC="ise"       P=pano_logic_g2     T="base"       F=hdmi2usb
   # PicoRV32     F=hdmi2usb
   - C=picorv32         TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=picorv32         TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=picorv32         TC="vivado"    P=mimas_a7          T="base"       F=hdmi2usb
   - C=picorv32         TC="vivado"    P=mimas_a7          T="net"        F=hdmi2usb
   - C=picorv32         TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=picorv32         TC="ise"       P=opsis             T="net"        F=hdmi2usb
   - C=picorv32.minimal TC="icestorm"  P=icebreaker        T="base"       F=stub
   - C=picorv32.minimal TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=picorv32.minimal TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=picorv32.minimal TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=picorv32.minimal TC="ise"       P=opsis             T="net"        F=hdmi2usb
   # minerva target     F=hdmi2usb
   - C=minerva          TC="vivado"    P=arty              T="base"       F=hdmi2usb
   - C=minerva          TC="vivado"    P=arty              T="net"        F=hdmi2usb
   - C=minerva          TC="ise"       P=opsis             T="base"       F=hdmi2usb
   - C=minerva          TC="ise"       P=opsis             T="net"        F=hdmi2usb
   #--------------------------------------------
   # Video Targets     F=hdmi2usb
   #--------------------------------------------
   - C=lm32             TC="vivado"    P=nexys_video       T="video"      F=hdmi2usb
   - C=lm32             TC="ise"       P=atlys             T="video"      F=hdmi2usb
   - C=lm32             TC="ise"       P=opsis             T="video"      F=hdmi2usb
   #--------------------------------------------
   # HDMI2USB Targets
   #--------------------------------------------
   - C=lm32             TC="ise"       P=atlys             T="hdmi2usb"   F=hdmi2usb
   - C=lm32             TC="ise"       P=opsis             T="hdmi2usb"   F=hdmi2usb
   #--------------------------------------------
   # MicroPython Targets
   #--------------------------------------------
   # FIXME: Add some here
   - C=vexriscv         TC="ise"       P=arty              T="base"       F=micropython  A="jobs = ${JOBS}"
   #--------------------------------------------
   # Linux Targets
   #--------------------------------------------
   - C=mor1kx.linux     TC="vivado"    P=arty              T="net"        F=linux        A="jobs = ${JOBS}"
   - C=mor1kx.linux     TC="vivado"    P=nexys_video       T="net"        F=linux        A="jobs = ${JOBS}"
   - C=mor1kx.linux     TC="ise"       P=atlys             T="net"        F=linux        A="jobs = ${JOBS}"
   - C=mor1kx.linux     TC="ise"       P=opsis             T="net"        F=linux        A="jobs = ${JOBS}"
   # FIXME: Add vexriscv.linux
   #- C=vexriscv.linux   TC="vivado"    P=arty              T="net"        F=linux
   #- C=vexriscv.linux   TC="ise"       P=opsis             T="net"        F=linux
   # FIXME: Add rocket.linux
   #--------------------------------------------
   # Zephyr Targets
   #--------------------------------------------
   - C=vexriscv.lite    TC="icestorm"  P=icebreaker        T="base"       F=zephyr       A="zephyr-app = hello_world;jobs = ${JOBS}"
   - C=vexriscv.lite    TC="vivado"    P=arty              T="net"        F=zephyr       A="zephyr-app = hello_world;jobs = ${JOBS}"
   - C=vexriscv.lite    TC="ise"       P=atlys             T="net"        F=zephyr       A="zephyr-app = hello_world;jobs = ${JOBS}"

# notifications:
#  email:
#   - hdmi2usb-spam@googlegroups.com
#  irc:
#   channels:
#    - "chat.freenode.net#hdmi2usb"
#   template:
#    - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"

